# see https://symfony.com/doc/current/reference/configuration/framework.html
framework:
    secret: '%env(APP_SECRET)%'
    #csrf_protection: true
    http_method_override: false

    # Enables session support. Note that the session will ONLY be started if you read or write from it.
    # Remove or comment this section to explicitly disable session support.
    session:
        handler_id: null
        cookie_secure: auto
        cookie_samesite: lax
        storage_factory_id: session.storage.factory.native

    #esi: true
    #fragments: true
    php_errors:
        log: true

    http_client:
        default_options:
            headers:
                'User-Agent': 'My Fancy App'
        scoped_clients:
            github.client:
                scope: 'https://api\.github\.com'
                headers:
                    Accept: 'application/vnd.github.v3+json'
#                    Authorization: 'token %env(GITHUB_API_TOKEN)%'
#            github.client:
#                base_uri: 'https://api.github.com'
#                headers:
#                    Accept: 'application/vnd.github.v3+json'
#                    Authorization: 'token %env(GITHUB_API_TOKEN)%'

when@test:
    framework:
        test: true
        session:
            storage_factory_id: session.storage.factory.mock_file
