# This file is the entry point to configure your own services.
# Files in the packages/ subdirectory configure your dependencies.

# Put parameters here that don't need to change on each machine where the app is deployed
# https://symfony.com/doc/current/best_practices.html#use-parameters-for-application-configuration
parameters:

services:
    # default configuration for services in *this* file
    _defaults:
        autowire: true      # Automatically injects dependencies in your services.
        autoconfigure: true # Automatically registers your services as commands, event subscribers, etc.

    App\:
        resource: '../src/'
        exclude:
            - '../src/Application/Contact'
            - '../src/DependencyInjection/'
            - '../src/Domain/Contact/Contact'
            - '../src/Domain/Contact/ContactId'
            - '../src/Domain/Organization/Organization'
            - '../src/Domain/Organization/OrganizationId'
            - '../src/Domain/Value'
            - '../src/Entity/'
            - '../src/Exception/'
            - '../src/Kernel.php'

    App\Application\Contact\ContactCommandHandler:
        arguments:
            - '@App\Domain\Contact\ContactRepository'
        tags:
            - { name: command_handler, handles: 'App\Application\Contact\ProposeContact', method: handleProposeContact }
            - { name: command_handler, handles: 'App\Application\Contact\ApproveContact', method: handleApproveContact }
            - { name: command_handler, handles: 'App\Application\Contact\RejectContact', method: handleRejectContact }
            - { name: command_handler, handles: 'App\Application\Contact\ModifyContact', method: handleModifyContact }
            - { name: command_handler, handles: 'App\Application\Contact\MergeContacts', method: handleMergeContacts }
            - { name: command_handler, handles: 'App\Application\Contact\DeleteContact', method: handleDeleteContact }